- name: cleanup rabbitmq configuration
  hosts: rabbitmq
  become: no
  serial: 3

  tasks:
  - name: remove vhosts
    community.rabbitmq.rabbitmq_vhost:
      name: "{{ item }}"
      state: absent
    with_items:
      - test1
      - test2
      - test3
    ignore_errors: yes
    tags:
      - rabbitmq

