---
# tasks file for metrics

- name: download node_exporter
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0644

- name: install node_exporter
  copy:
    src: /tmp/node_exporter-1.2.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: Create node_exporter user.
  user:
    name: node_exporter
    shell: /sbin/nologin
    state: present

- name: install node_exporter sysconfig
  copy:
    src: sysconfig.node_exporter
    dest: /etc/sysconfig/node_exporter
    owner: root
    group: root
    mode: 0644

- name: install systemd unit
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: node_exporter_service
  
- name: reload systemd daemon
  systemd:
    daemon_reload: true
  notify: restart node_exporter
  when: node_exporter_service is changed

- name: enable node_exporter service
  service:
    name: node_exporter
    enabled: yes
    state: started